import React, { useEffect, useState } from 'react';
import { BrandConfig } from '../types';
import { loadAutomationSettings, saveAutomationSettings, loadIntegrationKeys, saveIntegrationKeys, getBrandRegistryEntry, saveBrandRegistryEntry, forceSeedDefaultBrands, resetBrandToDefault } from '../services/storage';
import { loadUserProfile, UserProfile, getAuthToken } from '../services/auth';
import { autoGenerateDuneQueries } from '../services/analytics';
import { PricingPage } from './PricingPage';
import { checkCountLimit } from '../services/subscription';

interface SettingsProps {
    brandName: string;
    config: BrandConfig;
    onChange: (newConfig: BrandConfig) => void;
    onNavigateToBrandKit?: () => void;
    theme?: 'dark' | 'light';
    onThemeChange?: (theme: 'dark' | 'light') => void;
    initialTab?: SettingsTab;
}

export type SettingsTab = 'general' | 'notifications' | 'security' | 'billing';

export const Settings: React.FC<SettingsProps> = ({ brandName, config, onChange, onNavigateToBrandKit, theme = 'dark', onThemeChange, initialTab }) => {
    const [activeTab, setActiveTab] = useState<SettingsTab>(initialTab || 'general');
    const [automationEnabled, setAutomationEnabled] = useState(true);
    const darkModeEnabled = theme === 'dark';
    const [apifyHandle, setApifyHandle] = useState('');
    const [lunarSymbol, setLunarSymbol] = useState('');
    const [duneApiKey, setDuneApiKey] = useState('');
    const [duneVolumeQuery, setDuneVolumeQuery] = useState('');
    const [duneUsersQuery, setDuneUsersQuery] = useState('');
    const [duneRetentionQuery, setDuneRetentionQuery] = useState('');
    const [duneAutoGenerated, setDuneAutoGenerated] = useState(false);
    const [duneGenerating, setDuneGenerating] = useState(false);
    const [duneGenError, setDuneGenError] = useState('');
    const [showDuneKey, setShowDuneKey] = useState(false);
    const [savingIntegrations, setSavingIntegrations] = useState(false);
    const [timezone, setTimezone] = useState('UTC +0 (London)');
    const [language, setLanguage] = useState('English (US)');
    const [xApiKey, setXApiKey] = useState('');
    const [xApiSecret, setXApiSecret] = useState('');
    const [xAccessToken, setXAccessToken] = useState('');
    const [xAccessSecret, setXAccessSecret] = useState('');
    const [xConnectStatus, setXConnectStatus] = useState<{ connected: boolean; username?: string | null } | null>(null);
    const [xConnectError, setXConnectError] = useState('');
    const [xConnectLoading, setXConnectLoading] = useState(false);

    // Telegram state
    const [telegramLinkCode, setTelegramLinkCode] = useState('');
    const [telegramDeepLink, setTelegramDeepLink] = useState('');
    const [telegramLinkLoading, setTelegramLinkLoading] = useState(false);
    const [telegramLinkedChats, setTelegramLinkedChats] = useState<Array<{ chat_id: number; chat_title?: string; linked_by?: string; created_at?: string }>>([]);
    const [telegramError, setTelegramError] = useState('');

    // Profile data from auth
    const [userProfile, setUserProfile] = useState<UserProfile | null>(null);
    const [profileName, setProfileName] = useState('Alex Chen');
    const [profileEmail, setProfileEmail] = useState('alex@web3agency.io');
    const [profileRole, setProfileRole] = useState('Marketing Lead');
    const [profileCompany, setProfileCompany] = useState('Web3 Agency');

    // Competitor state
    const [settingsCompetitors, setSettingsCompetitors] = useState<Array<{ name: string; handle?: string; strengths?: string; weaknesses?: string }>>(config?.competitors || []);

    // Brand seeding state
    const [isSeeding, setIsSeeding] = useState(false);
    const [seedResult, setSeedResult] = useState<{ success: boolean; brands: string[] } | null>(null);
    const [isResetting, setIsResetting] = useState(false);

    useEffect(() => {
        const settings = loadAutomationSettings(brandName);
        setAutomationEnabled(settings.enabled);
        const keys = loadIntegrationKeys(brandName);
        setApifyHandle(keys.apify || '');
        setLunarSymbol(keys.lunarCrush || '');
        setDuneApiKey(keys.dune || '');
        setDuneVolumeQuery(keys.duneQueryIds?.volume || '');
        setDuneUsersQuery(keys.duneQueryIds?.users || '');
        setDuneRetentionQuery(keys.duneQueryIds?.retention || '');
        setDuneAutoGenerated(!!keys.duneAutoGenerated);

        // Load user profile from auth
        const profile = loadUserProfile();
        if (profile) {
            setUserProfile(profile);
            if (profile.fullName) setProfileName(profile.fullName);
            if (profile.email) setProfileEmail(profile.email);
            if (profile.role) setProfileRole(profile.role === 'founder' ? 'Founder / CEO' : profile.role.charAt(0).toUpperCase() + profile.role.slice(1));
        }
    }, [brandName]);

    useEffect(() => {
        let isActive = true;
        const fetchXStatus = async () => {
            try {
                const baseUrl = import.meta.env.VITE_API_BASE_URL || '';
                const registryEntry = getBrandRegistryEntry(brandName);
                const brandKey = registryEntry?.brandId || brandName;
                const response = await fetch(`${baseUrl}/api/auth/x/status?brandId=${encodeURIComponent(brandKey)}`);
                if (!response.ok) return;
                const data = await response.json();
                if (isActive) setXConnectStatus(data);
            } catch (e) {
                if (isActive) setXConnectStatus(null);
            }
        };
        fetchXStatus();
        return () => { isActive = false; };
    }, [brandName]);

    // Fetch Telegram linked chats
    useEffect(() => {
        let isActive = true;
        const fetchTelegramStatus = async () => {
            try {
                const baseUrl = import.meta.env.VITE_API_BASE_URL || '';
                const registryEntry = getBrandRegistryEntry(brandName);
                const brandKey = registryEntry?.brandId || brandName;
                const authToken = await getAuthToken();
                const response = await fetch(`${baseUrl}/api/telegram/status?brandId=${encodeURIComponent(brandKey)}`, {
                    headers: authToken ? { 'Authorization': `Bearer ${authToken}` } : {},
                });
                if (!response.ok) return;
                const data = await response.json();
                if (isActive) setTelegramLinkedChats(data.chats || []);
            } catch {
                if (isActive) setTelegramLinkedChats([]);
            }
        };
        fetchTelegramStatus();
        return () => { isActive = false; };
    }, [brandName]);

    const handleGenerateTelegramLink = async () => {
        setTelegramLinkLoading(true);
        setTelegramError('');
        setTelegramLinkCode('');
        setTelegramDeepLink('');
        try {
            const baseUrl = import.meta.env.VITE_API_BASE_URL || '';
            const registryEntry = getBrandRegistryEntry(brandName);
            const brandKey = registryEntry?.brandId || brandName;
            const authToken = await getAuthToken();
            const response = await fetch(`${baseUrl}/api/telegram/generate-link-code`, {
                method: 'POST',
                headers: {
                    'Content-Type': 'application/json',
                    ...(authToken ? { 'Authorization': `Bearer ${authToken}` } : {}),
                },
                body: JSON.stringify({ brandId: brandKey }),
            });
            const data = await response.json().catch(() => ({}));
            if (!response.ok) {
                setTelegramError(data?.error || 'Failed to generate link code');
                return;
            }
            setTelegramLinkCode(data.code);
            setTelegramDeepLink(data.deepLink || '');
        } catch (e: any) {
            setTelegramError(e?.message || 'Failed to generate link code');
        } finally {
            setTelegramLinkLoading(false);
        }
    };

    const handleUnlinkTelegram = async (chatId: number) => {
        try {
            const baseUrl = import.meta.env.VITE_API_BASE_URL || '';
            const registryEntry = getBrandRegistryEntry(brandName);
            const brandKey = registryEntry?.brandId || brandName;
            const authToken = await getAuthToken();
            const response = await fetch(`${baseUrl}/api/telegram/unlink`, {
                method: 'POST',
                headers: {
                    'Content-Type': 'application/json',
                    ...(authToken ? { 'Authorization': `Bearer ${authToken}` } : {}),
                },
                body: JSON.stringify({ brandId: brandKey, chatId }),
            });
            if (response.ok) {
                setTelegramLinkedChats(prev => prev.filter(c => c.chat_id !== chatId));
            }
        } catch {
            setTelegramError('Failed to unlink chat');
        }
    };

    const handleConnectX = async () => {
        setXConnectError('');
        setXConnectLoading(true);
        try {
            const baseUrl = import.meta.env.VITE_API_BASE_URL || '';
            const registryEntry = getBrandRegistryEntry(brandName);
            const brandKey = registryEntry?.brandId || brandName;
            const response = await fetch(`${baseUrl}/api/auth/x/authorize-url`, {
                method: 'POST',
                headers: { 'Content-Type': 'application/json' },
                body: JSON.stringify({ brandId: brandKey })
            });
            const data = await response.json().catch(() => ({}));
            if (!response.ok || !data?.url) {
                setXConnectError(data?.error || 'Failed to start X connection.');
                return;
            }
            window.location.href = data.url;
        } catch (e: any) {
            setXConnectError(e?.message || 'Failed to start X connection.');
        } finally {
            setXConnectLoading(false);
        }
    };

    const resolveBrandId = async (): Promise<string | null> => {
        const cached = getBrandRegistryEntry(brandName);
        if (cached?.brandId) return cached.brandId;

        try {
            const baseUrl = import.meta.env.VITE_API_BASE_URL || '';
            const authToken = await getAuthToken();
            const response = await fetch(`${baseUrl}/api/brands/resolve`, {
                method: 'POST',
                headers: {
                    'Content-Type': 'application/json',
                    ...(authToken ? { 'Authorization': `Bearer ${authToken}` } : {}),
                },
                body: JSON.stringify({ name: brandName })
            });

            if (!response.ok) return null;
            const data = await response.json();
            if (data?.id) {
                saveBrandRegistryEntry(brandName, data.id);
                return data.id;
            }
        } catch (e) {
            console.warn("Failed to resolve brand ID", e);
        }
        return null;
    };

    const handleAutomationToggle = async () => {
        const nextValue = !automationEnabled;
        setAutomationEnabled(nextValue);
        saveAutomationSettings(brandName, { enabled: nextValue, updatedAt: Date.now() });

        const brandId = await resolveBrandId();
        if (!brandId) return;

        try {
            const baseUrl = import.meta.env.VITE_API_BASE_URL || '';
            const authToken = await getAuthToken();
            await fetch(`${baseUrl}/api/brands/${brandId}/automation`, {
                method: 'PATCH',
                headers: {
                    'Content-Type': 'application/json',
                    ...(authToken ? { 'Authorization': `Bearer ${authToken}` } : {}),
                },
                body: JSON.stringify({
                    enabled: nextValue,
                    ownerId: null
                })
            });
        } catch (e) {
            console.warn("Failed to sync automation settings", e);
        }
    };

    const handleSaveIntegrations = async () => {
        setSavingIntegrations(true);
        const nextKeys = {
            apify: apifyHandle,
            lunarCrush: lunarSymbol,
            dune: duneApiKey,
            duneQueryIds: {
                volume: duneVolumeQuery,
                users: duneUsersQuery,
                retention: duneRetentionQuery
            },
            duneAutoGenerated,
        };
        saveIntegrationKeys(nextKeys, brandName);

        const brandId = await resolveBrandId();
        if (brandId) {
            try {
                const baseUrl = import.meta.env.VITE_API_BASE_URL || '';
                const authToken2 = await getAuthToken();
                await fetch(`${baseUrl}/api/brands/${brandId}/integrations`, {
                    method: 'PATCH',
                    headers: {
                        'Content-Type': 'application/json',
                        ...(authToken2 ? { 'Authorization': `Bearer ${authToken2}` } : {}),
                    },
                    body: JSON.stringify({
                        apifyHandle,
                        lunarcrushSymbol: lunarSymbol,
                        duneQueryIds: {
                            volume: duneVolumeQuery,
                            users: duneUsersQuery,
                            retention: duneRetentionQuery
                        },
                        xApiKey: xApiKey || undefined,
                        xApiSecret: xApiSecret || undefined,
                        xAccessToken: xAccessToken || undefined,
                        xAccessSecret: xAccessSecret || undefined
                    })
                });
            } catch (e) {
                console.warn("Failed to sync integrations", e);
            }
        }

        setSavingIntegrations(false);
    };

    const tabs: { id: SettingsTab; label: string; icon: string; disabled?: boolean }[] = [
        { id: 'general', label: 'General', icon: 'person' },
        { id: 'notifications', label: 'Notifications', icon: 'notifications', disabled: true },
        { id: 'security', label: 'Security', icon: 'shield', disabled: true },
        { id: 'billing', label: 'Billing', icon: 'credit_card' },
    ];

    return (
        <div className="flex-1 flex flex-col min-h-0" style={{ backgroundColor: 'var(--bg-primary)' }}>
            {/* Header */}
            <div className="flex items-center justify-between px-10 py-6 border-b" style={{ borderColor: 'var(--border)' }}>
                <div className="flex flex-col gap-1">
                    <h1 className="text-2xl font-bold" style={{ color: 'var(--text-primary)' }}>Settings</h1>
                    <p className="text-sm" style={{ color: 'var(--text-muted)' }}>Manage your account and brand settings</p>
                </div>
            </div>

            {/* Main Content */}
            <div className="flex-1 flex gap-8 px-10 py-7 overflow-hidden">
                {/* Tabs Column */}
                <div className="w-[220px] flex flex-col gap-1 flex-shrink-0">
                    {tabs.map(tab => (
                        <button
                            key={tab.id}
                            onClick={() => !tab.disabled && setActiveTab(tab.id)}
                            disabled={tab.disabled}
                            className={`flex items-center gap-3 px-4 py-3 rounded-lg text-left transition-colors ${
                                tab.disabled
                                    ? 'cursor-not-allowed'
                                    : activeTab === tab.id
                                        ? 'bg-[#FF5C00] text-white'
                                        : ''
                            }`}
                            style={tab.disabled ? { color: 'var(--text-faint)' } : activeTab !== tab.id ? { color: 'var(--text-muted)' } : undefined}
                        >
                            <span
                                className="material-symbols-sharp text-xl"
                                style={{ fontVariationSettings: activeTab === tab.id ? "'FILL' 1, 'wght' 300" : "'wght' 300" }}
                            >
                                {tab.icon}
                            </span>
                            <span className="text-sm font-medium">{tab.label}</span>
                            {tab.disabled && <span className="text-[10px] text-[#3A3A3F] ml-auto">Soon</span>}
                        </button>
                    ))}

                    {/* Divider */}
                    <div className="h-px bg-[#1F1F23] my-2"></div>

                    {/* Brand Kit Link */}
                    <button
                        onClick={onNavigateToBrandKit}
                        className="flex items-center gap-3 px-4 py-3 rounded-lg text-left border border-[#FF5C0044] text-[#FF5C00] hover:bg-[#FF5C0011] transition-colors"
                    >
                        <span className="material-symbols-sharp text-xl" style={{ fontVariationSettings: "'wght' 300" }}>palette</span>
                        <span className="text-sm font-medium">Brand Kit</span>
                    </button>
                </div>

                {/* Settings Panel */}
                <div className="flex-1 flex flex-col gap-6 overflow-y-auto">
                    {activeTab === 'general' && (
                        <>
                            {/* Profile Information Card */}
                            <div className="rounded-[14px] p-6" style={{ backgroundColor: 'var(--bg-secondary)', border: '1px solid var(--border)', boxShadow: 'var(--card-shadow)' }}>
                                <div className="flex items-center justify-between mb-5">
                                    <span className="text-base font-semibold" style={{ color: 'var(--text-primary)' }}>Profile Information</span>
                                    <button className="text-[#FF5C00] text-sm font-medium hover:underline">Edit</button>
                                </div>

                                <div className="flex gap-6">
                                    {/* Avatar */}
                                    <div className="w-20 h-20 rounded-full bg-[#FF5C00] flex items-center justify-center flex-shrink-0">
                                        <span className="text-white text-[28px] font-semibold">AC</span>
                                    </div>

                                    {/* Fields */}
                                    <div className="flex-1 flex flex-col gap-4">
                                        <div className="flex gap-4">
                                            <div className="flex-1 flex flex-col gap-1.5">
                                                <span className="text-[#6B6B70] text-xs">Full Name</span>
                                                <span className="text-white text-sm">{profileName}</span>
                                            </div>
                                            <div className="flex-1 flex flex-col gap-1.5">
                                                <span className="text-[#6B6B70] text-xs">Email</span>
                                                <span className="text-white text-sm">{profileEmail}</span>
                                            </div>
                                        </div>
                                        <div className="flex gap-4">
                                            <div className="flex-1 flex flex-col gap-1.5">
                                                <span className="text-[#6B6B70] text-xs">Role</span>
                                                <span className="text-white text-sm">{profileRole}</span>
                                            </div>
                                            <div className="flex-1 flex flex-col gap-1.5">
                                                <span className="text-[#6B6B70] text-xs">Company</span>
                                                <span className="text-white text-sm">{profileCompany}</span>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>

                            {/* Preferences Card */}
                            <div className="rounded-[14px] p-6" style={{ backgroundColor: 'var(--bg-secondary)', border: '1px solid var(--border)', boxShadow: 'var(--card-shadow)' }}>
                                <span className="text-base font-semibold mb-5 block" style={{ color: 'var(--text-primary)' }}>Preferences</span>

                                <div className="flex flex-col gap-4">
                                    {/* Timezone */}
                                    <div className="flex items-center justify-between py-2">
                                        <div className="flex flex-col gap-1">
                                            <span className="text-white text-sm">Timezone</span>
                                            <span className="text-[#6B6B70] text-xs">Detected from your browser</span>
                                        </div>
                                        <span className="text-[#6B6B70] text-[13px]">{timezone}</span>
                                    </div>

                                    <div className="h-px bg-[#1F1F23]"></div>

                                    {/* Language */}
                                    <div className="flex items-center justify-between py-2">
                                        <div className="flex flex-col gap-1">
                                            <span className="text-white text-sm">Language</span>
                                            <span className="text-[#6B6B70] text-xs">Interface language</span>
                                        </div>
                                        <span className="text-[#6B6B70] text-[13px]">{language}</span>
                                    </div>

                                    <div className="h-px bg-[#1F1F23]"></div>

                                    {/* Appearance */}
                                    <div className="flex items-center justify-between py-2">
                                        <div className="flex flex-col gap-1">
                                            <span style={{ color: 'var(--text-primary)' }} className="text-sm">Appearance</span>
                                            <span style={{ color: 'var(--text-muted)' }} className="text-xs">
                                                {darkModeEnabled ? 'Dark mode' : 'Light mode'} active
                                            </span>
                                        </div>
                                        <div className="flex items-center gap-2">
                                            <span className="material-symbols-sharp text-lg" style={{ color: darkModeEnabled ? 'var(--accent)' : 'var(--text-muted)', fontVariationSettings: "'wght' 200, 'FILL' 1" }}>
                                                {darkModeEnabled ? 'dark_mode' : 'light_mode'}
                                            </span>
                                            <button
                                                onClick={() => onThemeChange?.(darkModeEnabled ? 'light' : 'dark')}
                                                className={`relative w-11 h-6 rounded-full transition-colors ${darkModeEnabled ? 'bg-[#FF5C00]' : 'bg-[#D1D1D6]'}`}
                                            >
                                                <span
                                                    className={`absolute top-0.5 w-5 h-5 rounded-full bg-white transition-transform shadow-sm ${darkModeEnabled ? 'left-[22px]' : 'left-0.5'}`}
                                                ></span>
                                            </button>
                                        </div>
                                    </div>
                                </div>
                            </div>

                            {/* Competitors Card */}
                            <div className="rounded-[14px] p-6" style={{ backgroundColor: 'var(--bg-secondary)', border: '1px solid var(--border)', boxShadow: 'var(--card-shadow)' }}>
                                <div className="flex items-center justify-between mb-2">
                                    <span className="text-base font-semibold" style={{ color: 'var(--text-primary)' }}>Competitive Intelligence</span>
                                    {(() => {
                                        const compLimit = checkCountLimit(config.subscription, 'maxCompetitors', settingsCompetitors.length);
                                        return compLimit.allowed ? (
                                            <button
                                                onClick={() => {
                                                    const updated = [...settingsCompetitors, { name: '', handle: '' }];
                                                    setSettingsCompetitors(updated);
                                                }}
                                                className="text-xs text-[#FF5C00] hover:text-[#FF6B1A] font-medium"
                                            >
                                                + Add Competitor {compLimit.max > 0 && <span className="text-[#6B6B70]">({settingsCompetitors.length}/{compLimit.max})</span>}
                                            </button>
                                        ) : (
                                            <button
                                                onClick={() => setActiveTab('billing')}
                                                className="text-xs text-[#FF5C00] hover:text-[#FF6B1A] font-medium transition-colors"
                                            >
                                                Limit reached ({compLimit.current}/{compLimit.max}) — Upgrade →
                                            </button>
                                        );
                                    })()}
                                </div>
                                <p className="text-[#6B6B70] text-xs mb-4">Add competitors so the AI CMO can differentiate your brand and find competitive gaps.</p>

                                {settingsCompetitors.length === 0 ? (
                                    <div className="text-center py-6 text-[#6B6B70] text-sm">
                                        <span className="material-symbols-sharp text-2xl block mb-1" style={{ fontVariationSettings: "'wght' 300" }}>swords</span>
                                        No competitors added yet. Click "+ Add Competitor" to start.
                                    </div>
                                ) : (
                                    <div className="space-y-3">
                                        {settingsCompetitors.map((comp, idx) => (
                                            <div key={idx} className="flex gap-2 items-start">
                                                <div className="flex-1 grid grid-cols-2 gap-2">
                                                    <input
                                                        value={comp.name}
                                                        onChange={(e) => {
                                                            const updated = [...settingsCompetitors];
                                                            updated[idx] = { ...updated[idx], name: e.target.value };
                                                            setSettingsCompetitors(updated);
                                                        }}
                                                        placeholder="Competitor name"
                                                        className="h-[38px] rounded-lg bg-[#0D0D0F] border border-[#2A2A2E] px-3 text-white text-sm placeholder-[#6B6B70] focus:border-[#FF5C00] focus:outline-none transition-colors"
                                                    />
                                                    <input
                                                        value={comp.handle || ''}
                                                        onChange={(e) => {
                                                            const updated = [...settingsCompetitors];
                                                            updated[idx] = { ...updated[idx], handle: e.target.value.replace(/^@/, '') };
                                                            setSettingsCompetitors(updated);
                                                        }}
                                                        placeholder="@handle"
                                                        className="h-[38px] rounded-lg bg-[#0D0D0F] border border-[#2A2A2E] px-3 text-white text-sm placeholder-[#6B6B70] focus:border-[#FF5C00] focus:outline-none transition-colors"
                                                    />
                                                    <input
                                                        value={comp.strengths || ''}
                                                        onChange={(e) => {
                                                            const updated = [...settingsCompetitors];
                                                            updated[idx] = { ...updated[idx], strengths: e.target.value };
                                                            setSettingsCompetitors(updated);
                                                        }}
                                                        placeholder="Their strengths (optional)"
                                                        className="h-[38px] rounded-lg bg-[#0D0D0F] border border-[#2A2A2E] px-3 text-white text-sm placeholder-[#6B6B70] focus:border-[#FF5C00] focus:outline-none transition-colors"
                                                    />
                                                    <input
                                                        value={comp.weaknesses || ''}
                                                        onChange={(e) => {
                                                            const updated = [...settingsCompetitors];
                                                            updated[idx] = { ...updated[idx], weaknesses: e.target.value };
                                                            setSettingsCompetitors(updated);
                                                        }}
                                                        placeholder="Their weaknesses (optional)"
                                                        className="h-[38px] rounded-lg bg-[#0D0D0F] border border-[#2A2A2E] px-3 text-white text-sm placeholder-[#6B6B70] focus:border-[#FF5C00] focus:outline-none transition-colors"
                                                    />
                                                </div>
                                                <button
                                                    onClick={() => setSettingsCompetitors(settingsCompetitors.filter((_, i) => i !== idx))}
                                                    className="w-[38px] h-[38px] rounded-lg bg-[#0D0D0F] border border-[#2A2A2E] flex items-center justify-center text-[#6B6B70] hover:text-red-400 hover:border-red-400/30 transition-colors flex-shrink-0"
                                                >
                                                    <span className="material-symbols-sharp text-lg" style={{ fontVariationSettings: "'wght' 300" }}>close</span>
                                                </button>
                                            </div>
                                        ))}
                                    </div>
                                )}

                                <button
                                    onClick={() => {
                                        const validComps = settingsCompetitors.filter(c => c.name.trim());
                                        onChange({ ...config, competitors: validComps.length > 0 ? validComps : undefined });
                                    }}
                                    className="mt-4 px-4 py-2 rounded-lg bg-[#FF5C00] text-white text-sm font-medium hover:bg-[#FF6B1A] transition-colors"
                                >
                                    Save Competitors
                                </button>
                            </div>

                            {/* Integrations Card (preserving existing functionality) */}
                            <div className="rounded-[14px] p-6" style={{ backgroundColor: 'var(--bg-secondary)', border: '1px solid var(--border)', boxShadow: 'var(--card-shadow)' }}>
                                <span className="text-base font-semibold mb-2 block" style={{ color: 'var(--text-primary)' }}>Data Integrations</span>
                                <p className="text-[#6B6B70] text-xs mb-5">Connect per-brand data sources to improve analytics and agent accuracy.</p>

                                <div className="grid grid-cols-2 gap-4 mb-4">
                                    <div className="flex flex-col gap-2">
                                        <label className="text-[#9CA3AF] text-xs font-medium">Apify / X Handle</label>
                                        <input
                                            value={apifyHandle}
                                            onChange={(e) => setApifyHandle(e.target.value)}
                                            placeholder="@yourbrand"
                                            className="rounded-lg px-3.5 py-3 text-sm outline-none transition-colors" style={{ backgroundColor: 'var(--bg-tertiary)', border: '1px solid var(--border-subtle)', color: 'var(--text-primary)' }}
                                        />
                                    </div>
                                    <div className="flex flex-col gap-2">
                                        <label className="text-[#9CA3AF] text-xs font-medium">LunarCrush Symbol</label>
                                        <input
                                            value={lunarSymbol}
                                            onChange={(e) => setLunarSymbol(e.target.value)}
                                            placeholder="ETH, METIS, etc."
                                            className="rounded-lg px-3.5 py-3 text-sm outline-none transition-colors" style={{ backgroundColor: 'var(--bg-tertiary)', border: '1px solid var(--border-subtle)', color: 'var(--text-primary)' }}
                                        />
                                    </div>
                                </div>

                                {/* Dune API Key + Auto-Generate */}
                                <div className="mb-5">
                                    <div className="flex flex-col gap-2 mb-3">
                                        <label className="text-[#9CA3AF] text-xs font-medium">Dune Analytics API Key</label>
                                        <div className="flex gap-2">
                                            <div className="flex-1 relative">
                                                <input
                                                    type={showDuneKey ? 'text' : 'password'}
                                                    value={duneApiKey}
                                                    onChange={(e) => setDuneApiKey(e.target.value)}
                                                    placeholder="Paste your Dune API key"
                                                    className="w-full rounded-lg px-3.5 py-3 text-sm outline-none transition-colors pr-10" style={{ backgroundColor: 'var(--bg-tertiary)', border: '1px solid var(--border-subtle)', color: 'var(--text-primary)' }}
                                                />
                                                <button
                                                    type="button"
                                                    onClick={() => setShowDuneKey(!showDuneKey)}
                                                    className="absolute right-3 top-1/2 -translate-y-1/2 text-[#6B6B70] hover:text-[#9CA3AF] transition-colors"
                                                >
                                                    <span className="material-symbols-sharp text-base" style={{ fontVariationSettings: "'wght' 300" }}>
                                                        {showDuneKey ? 'visibility_off' : 'visibility'}
                                                    </span>
                                                </button>
                                            </div>
                                            {duneApiKey && config?.blockchain?.contracts?.length > 0 && (
                                                <button
                                                    onClick={async () => {
                                                        setDuneGenerating(true);
                                                        setDuneGenError('');
                                                        try {
                                                            const queryIds = await autoGenerateDuneQueries(
                                                                duneApiKey,
                                                                config.blockchain!.contracts,
                                                                brandName
                                                            );
                                                            if (queryIds) {
                                                                if (queryIds.volume) setDuneVolumeQuery(queryIds.volume);
                                                                if (queryIds.users) setDuneUsersQuery(queryIds.users);
                                                                if (queryIds.retention) setDuneRetentionQuery(queryIds.retention);
                                                                setDuneAutoGenerated(true);
                                                                // Save immediately
                                                                const currentKeys = loadIntegrationKeys(brandName);
                                                                saveIntegrationKeys({
                                                                    ...currentKeys,
                                                                    dune: duneApiKey,
                                                                    duneQueryIds: queryIds,
                                                                    duneAutoGenerated: true,
                                                                }, brandName);
                                                            } else {
                                                                setDuneGenError('Failed to generate queries. Check your API key and try again.');
                                                            }
                                                        } catch {
                                                            setDuneGenError('Failed to generate queries.');
                                                        } finally {
                                                            setDuneGenerating(false);
                                                        }
                                                    }}
                                                    disabled={duneGenerating}
                                                    className="px-4 py-3 rounded-lg text-sm font-medium whitespace-nowrap transition-colors flex items-center gap-2"
                                                    style={{
                                                        backgroundColor: duneGenerating ? 'var(--bg-tertiary)' : '#FF5C00',
                                                        color: duneGenerating ? 'var(--text-muted)' : 'white',
                                                    }}
                                                >
                                                    {duneGenerating ? (
                                                        <>
                                                            <span className="animate-spin inline-block w-3.5 h-3.5 border-2 border-current border-t-transparent rounded-full" />
                                                            Generating...
                                                        </>
                                                    ) : (
                                                        <>
                                                            <span className="material-symbols-sharp text-base" style={{ fontVariationSettings: "'wght' 300" }}>auto_fix_high</span>
                                                            Auto-Generate Queries
                                                        </>
                                                    )}
                                                </button>
                                            )}
                                        </div>
                                        {duneGenError && (
                                            <p className="text-xs text-red-400 mt-1">{duneGenError}</p>
                                        )}
                                        {duneAutoGenerated && !duneGenError && (
                                            <p className="text-xs text-[#22C55E] mt-1 flex items-center gap-1">
                                                <span className="material-symbols-sharp text-sm" style={{ fontVariationSettings: "'wght' 300" }}>check_circle</span>
                                                Queries auto-generated from your contract addresses
                                            </p>
                                        )}
                                        <p className="text-[#6B6B70] text-[11px] mt-0.5">
                                            Get a free key at dune.com → Settings → API. Requires Analyst plan for auto-generation.
                                        </p>
                                    </div>
                                </div>

                                <div className="grid grid-cols-3 gap-4 mb-5">
                                    <div className="flex flex-col gap-2">
                                        <label className="text-[#9CA3AF] text-xs font-medium">Dune Volume Query {duneAutoGenerated && <span className="text-[#6B6B70]">(auto)</span>}</label>
                                        <input
                                            value={duneVolumeQuery}
                                            onChange={(e) => { setDuneVolumeQuery(e.target.value); setDuneAutoGenerated(false); }}
                                            placeholder="Query ID"
                                            className="rounded-lg px-3.5 py-3 text-sm outline-none transition-colors" style={{ backgroundColor: 'var(--bg-tertiary)', border: '1px solid var(--border-subtle)', color: 'var(--text-primary)' }}
                                        />
                                    </div>
                                    <div className="flex flex-col gap-2">
                                        <label className="text-[#9CA3AF] text-xs font-medium">Dune Users Query {duneAutoGenerated && <span className="text-[#6B6B70]">(auto)</span>}</label>
                                        <input
                                            value={duneUsersQuery}
                                            onChange={(e) => { setDuneUsersQuery(e.target.value); setDuneAutoGenerated(false); }}
                                            placeholder="Query ID"
                                            className="rounded-lg px-3.5 py-3 text-sm outline-none transition-colors" style={{ backgroundColor: 'var(--bg-tertiary)', border: '1px solid var(--border-subtle)', color: 'var(--text-primary)' }}
                                        />
                                    </div>
                                    <div className="flex flex-col gap-2">
                                        <label className="text-[#9CA3AF] text-xs font-medium">Dune Retention Query {duneAutoGenerated && <span className="text-[#6B6B70]">(auto)</span>}</label>
                                        <input
                                            value={duneRetentionQuery}
                                            onChange={(e) => { setDuneRetentionQuery(e.target.value); setDuneAutoGenerated(false); }}
                                            placeholder="Query ID"
                                            className="rounded-lg px-3.5 py-3 text-sm outline-none transition-colors" style={{ backgroundColor: 'var(--bg-tertiary)', border: '1px solid var(--border-subtle)', color: 'var(--text-primary)' }}
                                        />
                                    </div>
                                </div>

                                <div className="border-t border-[#1F1F23] pt-4 mb-4">
                                    <span className="text-xs font-semibold text-[#94A3B8] uppercase tracking-widest">X Account (Recommended)</span>
                                    <p className="text-[11px] text-[#6B6B70] mt-1 mb-3">
                                        Connect your official X account for the most accurate follower + engagement tracking.
                                        If you skip this, we'll use public data for the handle above.
                                    </p>
                                    <div className="flex items-center gap-3">
                                        <button
                                            onClick={handleConnectX}
                                            disabled={xConnectLoading}
                                            className="px-4 py-2 rounded-lg bg-[#1A1A1D] border border-[#2E2E2E] text-white text-sm font-semibold hover:border-[#FF5C00] disabled:opacity-50"
                                        >
                                            {xConnectLoading ? 'Connecting...' : (xConnectStatus?.connected ? 'Reconnect X' : 'Connect X')}
                                        </button>
                                        <span className={`text-xs ${xConnectStatus?.connected ? 'text-green-400' : 'text-[#6B6B70]'}`}>
                                            {xConnectStatus?.connected ? `Connected as @${xConnectStatus?.username || 'account'}` : 'Not connected'}
                                        </span>
                                    </div>
                                    {xConnectError && (
                                        <p className="text-xs text-red-400 mt-2">{xConnectError}</p>
                                    )}
                                </div>

                                <div className="mt-4 border-t border-[#1F1F23] pt-4">
                                    <span className="text-xs font-semibold text-[#94A3B8] uppercase tracking-widest">X Publishing Credentials</span>
                                    <p className="text-[11px] text-[#6B6B70] mt-1 mb-3">
                                        Stored securely in Supabase for server-side publishing. Leave blank to keep existing values.
                                    </p>
                                    <div className="grid grid-cols-2 gap-4 mb-4">
                                        <div className="flex flex-col gap-2">
                                            <label className="text-[#9CA3AF] text-xs font-medium">X API Key</label>
                                            <input
                                                value={xApiKey}
                                                onChange={(e) => setXApiKey(e.target.value)}
                                                placeholder="API Key"
                                                className="rounded-lg px-3.5 py-3 text-sm outline-none transition-colors" style={{ backgroundColor: 'var(--bg-tertiary)', border: '1px solid var(--border-subtle)', color: 'var(--text-primary)' }}
                                            />
                                        </div>
                                        <div className="flex flex-col gap-2">
                                            <label className="text-[#9CA3AF] text-xs font-medium">X API Secret</label>
                                            <input
                                                type="password"
                                                value={xApiSecret}
                                                onChange={(e) => setXApiSecret(e.target.value)}
                                                placeholder="API Secret"
                                                className="rounded-lg px-3.5 py-3 text-sm outline-none transition-colors" style={{ backgroundColor: 'var(--bg-tertiary)', border: '1px solid var(--border-subtle)', color: 'var(--text-primary)' }}
                                            />
                                        </div>
                                    </div>
                                    <div className="grid grid-cols-2 gap-4">
                                        <div className="flex flex-col gap-2">
                                            <label className="text-[#9CA3AF] text-xs font-medium">X Access Token</label>
                                            <input
                                                type="password"
                                                value={xAccessToken}
                                                onChange={(e) => setXAccessToken(e.target.value)}
                                                placeholder="Access Token"
                                                className="rounded-lg px-3.5 py-3 text-sm outline-none transition-colors" style={{ backgroundColor: 'var(--bg-tertiary)', border: '1px solid var(--border-subtle)', color: 'var(--text-primary)' }}
                                            />
                                        </div>
                                        <div className="flex flex-col gap-2">
                                            <label className="text-[#9CA3AF] text-xs font-medium">X Access Secret</label>
                                            <input
                                                type="password"
                                                value={xAccessSecret}
                                                onChange={(e) => setXAccessSecret(e.target.value)}
                                                placeholder="Access Secret"
                                                className="rounded-lg px-3.5 py-3 text-sm outline-none transition-colors" style={{ backgroundColor: 'var(--bg-tertiary)', border: '1px solid var(--border-subtle)', color: 'var(--text-primary)' }}
                                            />
                                        </div>
                                    </div>
                                </div>

                                <div className="flex justify-end">
                                    <button
                                        onClick={handleSaveIntegrations}
                                        disabled={savingIntegrations}
                                        className="flex items-center gap-2 px-5 py-2.5 rounded-lg text-white text-sm font-semibold disabled:opacity-50"
                                        style={{ background: 'linear-gradient(180deg, #FF5C00 0%, #FF8400 100%)' }}
                                    >
                                        {savingIntegrations ? (
                                            <>
                                                <span className="material-symbols-sharp text-base animate-spin" style={{ fontVariationSettings: "'wght' 300" }}>progress_activity</span>
                                                Saving...
                                            </>
                                        ) : (
                                            'Save Integrations'
                                        )}
                                    </button>
                                </div>
                            </div>

                            {/* Telegram Bot Integration Card */}
                            <div className="rounded-xl border border-[#1F1F23] bg-[#111113] p-6 space-y-4">
                                <div className="flex items-center gap-3 mb-1">
                                    <div className="w-8 h-8 rounded-lg bg-[#0088CC]/10 flex items-center justify-center">
                                        <span className="material-symbols-sharp text-[#0088CC]" style={{ fontSize: 18 }}>send</span>
                                    </div>
                                    <div>
                                        <h3 className="text-white text-sm font-semibold">Telegram Bot</h3>
                                        <p className="text-[11px] text-[#6B6B70]">AI co-pilot in your Telegram group</p>
                                    </div>
                                    <span className={`ml-auto text-[10px] font-semibold px-2 py-0.5 rounded-full ${telegramLinkedChats.length > 0 ? 'bg-green-500/10 text-green-400' : 'bg-[#1F1F23] text-[#6B6B70]'}`}>
                                        {telegramLinkedChats.length > 0 ? 'Connected' : 'Not connected'}
                                    </span>
                                </div>

                                <p className="text-[#A0A0A6] text-[13px] leading-relaxed">
                                    Connect the Defia bot to your Telegram group for automated daily briefings, AI recommendations, and natural language content creation.
                                </p>

                                {/* Linked chats */}
                                {telegramLinkedChats.length > 0 && (
                                    <div className="space-y-2">
                                        <span className="text-xs font-semibold text-[#94A3B8] uppercase tracking-widest">Linked Groups</span>
                                        {telegramLinkedChats.map(chat => (
                                            <div key={chat.chat_id} className="flex items-center gap-3 p-3 rounded-lg bg-[#0A0A0B] border border-[#1F1F23]">
                                                <span className="material-symbols-sharp text-[#0088CC]" style={{ fontSize: 16 }}>group</span>
                                                <div className="flex-1 min-w-0">
                                                    <p className="text-white text-sm font-medium truncate">{chat.chat_title || `Chat ${chat.chat_id}`}</p>
                                                    <p className="text-[#6B6B70] text-[11px]">
                                                        {chat.linked_by ? `Linked by @${chat.linked_by}` : 'Linked'}
                                                        {chat.created_at ? ` • ${new Date(chat.created_at).toLocaleDateString()}` : ''}
                                                    </p>
                                                </div>
                                                <button
                                                    onClick={() => handleUnlinkTelegram(chat.chat_id)}
                                                    className="text-[#6B6B70] hover:text-red-400 transition-colors text-xs"
                                                >
                                                    Unlink
                                                </button>
                                            </div>
                                        ))}
                                    </div>
                                )}

                                {/* Generate link code */}
                                {!telegramLinkCode ? (
                                    <button
                                        onClick={handleGenerateTelegramLink}
                                        disabled={telegramLinkLoading}
                                        className="flex items-center gap-2 px-4 py-2.5 rounded-lg bg-[#0088CC]/10 border border-[#0088CC]/20 text-[#0088CC] text-sm font-semibold hover:bg-[#0088CC]/20 disabled:opacity-50 transition-colors"
                                    >
                                        {telegramLinkLoading ? (
                                            <>
                                                <span className="material-symbols-sharp text-base animate-spin" style={{ fontVariationSettings: "'wght' 300" }}>progress_activity</span>
                                                Generating...
                                            </>
                                        ) : (
                                            <>
                                                <span className="material-symbols-sharp text-base">link</span>
                                                {telegramLinkedChats.length > 0 ? 'Link Another Group' : 'Generate Link Code'}
                                            </>
                                        )}
                                    </button>
                                ) : (
                                    <div className="space-y-3 p-4 rounded-lg bg-[#0A0A0B] border border-[#0088CC]/20">
                                        <div className="flex items-center gap-2">
                                            <span className="material-symbols-sharp text-green-400" style={{ fontSize: 16 }}>check_circle</span>
                                            <span className="text-white text-sm font-semibold">Link Code Generated</span>
                                        </div>

                                        <div className="flex items-center gap-2">
                                            <code className="flex-1 px-3 py-2 rounded bg-[#1F1F23] text-[#FF5C00] text-sm font-mono font-bold tracking-wider text-center">
                                                {telegramLinkCode}
                                            </code>
                                            <button
                                                onClick={() => navigator.clipboard.writeText(telegramLinkCode)}
                                                className="p-2 rounded-lg hover:bg-[#1F1F23] text-[#6B6B70] hover:text-white transition-colors"
                                                title="Copy code"
                                            >
                                                <span className="material-symbols-sharp" style={{ fontSize: 16 }}>content_copy</span>
                                            </button>
                                        </div>

                                        {telegramDeepLink && (
                                            <a
                                                href={telegramDeepLink}
                                                target="_blank"
                                                rel="noopener noreferrer"
                                                className="flex items-center justify-center gap-2 px-4 py-2.5 rounded-lg bg-[#0088CC] text-white text-sm font-semibold hover:bg-[#0077B5] transition-colors"
                                            >
                                                <span className="material-symbols-sharp text-base">open_in_new</span>
                                                Add Bot to Telegram Group
                                            </a>
                                        )}

                                        <div className="text-[#6B6B70] text-[11px] space-y-1">
                                            <p>1. Click the button above to add the bot to your group</p>
                                            <p>2. The bot will auto-link using your code</p>
                                            <p>3. Code expires in 30 minutes</p>
                                        </div>
                                    </div>
                                )}

                                {telegramError && (
                                    <p className="text-xs text-red-400">{telegramError}</p>
                                )}
                            </div>

                            {/* Brand Data Management Card */}
                            <div className="rounded-[14px] p-6" style={{ backgroundColor: 'var(--bg-secondary)', border: '1px solid var(--border)', boxShadow: 'var(--card-shadow)' }}>
                                <div className="flex items-center gap-3 mb-2">
                                    <span className="material-symbols-sharp text-[#FF5C00] text-xl" style={{ fontVariationSettings: "'wght' 300" }}>database</span>
                                    <span className="text-base font-semibold" style={{ color: 'var(--text-primary)' }}>Brand Data Management</span>
                                </div>
                                <p className="text-[#6B6B70] text-xs mb-5">Import demo brands or reset your current brand to its default configuration.</p>

                                <div className="flex flex-col gap-4">
                                    {/* Seed Default Brands */}
                                    <div className="flex items-center justify-between py-3 px-4 bg-[#1A1A1D] rounded-lg border border-[#2E2E2E]">
                                        <div className="flex flex-col gap-1">
                                            <span className="text-white text-sm font-medium">Import Demo Brands</span>
                                            <span className="text-[#6B6B70] text-xs">Add ENKI, Netswap, Metis, and LazAI with all their data</span>
                                        </div>
                                        <button
                                            onClick={async () => {
                                                setIsSeeding(true);
                                                setSeedResult(null);
                                                try {
                                                    const result = await forceSeedDefaultBrands();
                                                    setSeedResult(result);
                                                } finally {
                                                    setIsSeeding(false);
                                                }
                                            }}
                                            disabled={isSeeding}
                                            className="flex items-center gap-2 px-4 py-2 rounded-lg bg-[#22C55E] hover:bg-[#16A34A] text-white text-sm font-medium disabled:opacity-50 transition-colors"
                                        >
                                            {isSeeding ? (
                                                <>
                                                    <span className="material-symbols-sharp text-base animate-spin" style={{ fontVariationSettings: "'wght' 300" }}>progress_activity</span>
                                                    Importing...
                                                </>
                                            ) : (
                                                <>
                                                    <span className="material-symbols-sharp text-base" style={{ fontVariationSettings: "'wght' 300" }}>download</span>
                                                    Import Brands
                                                </>
                                            )}
                                        </button>
                                    </div>

                                    {/* Seed Result */}
                                    {seedResult && (
                                        <div className={`p-3 rounded-lg border ${seedResult.success ? 'bg-[#22C55E]/10 border-[#22C55E]/30' : 'bg-red-500/10 border-red-500/30'}`}>
                                            <div className="flex items-center gap-2">
                                                <span className={`material-symbols-sharp text-base ${seedResult.success ? 'text-[#22C55E]' : 'text-red-400'}`} style={{ fontVariationSettings: "'FILL' 1, 'wght' 300" }}>
                                                    {seedResult.success ? 'check_circle' : 'error'}
                                                </span>
                                                <span className={`text-sm font-medium ${seedResult.success ? 'text-[#22C55E]' : 'text-red-400'}`}>
                                                    {seedResult.success
                                                        ? `Successfully imported: ${seedResult.brands.join(', ')}`
                                                        : 'Failed to import brands'}
                                                </span>
                                            </div>
                                            {seedResult.success && (
                                                <p className="text-[#6B6B70] text-xs mt-1 ml-6">Refresh the page or use the sidebar to switch to these brands.</p>
                                            )}
                                        </div>
                                    )}

                                    <div className="h-px bg-[#2E2E2E]"></div>

                                    {/* Reset Current Brand */}
                                    <div className="flex items-center justify-between py-3 px-4 bg-[#1A1A1D] rounded-lg border border-[#2E2E2E]">
                                        <div className="flex flex-col gap-1">
                                            <span className="text-white text-sm font-medium">Reset Current Brand</span>
                                            <span className="text-[#6B6B70] text-xs">Restore "{brandName}" to its default configuration</span>
                                        </div>
                                        <button
                                            onClick={async () => {
                                                if (!confirm(`Are you sure you want to reset "${brandName}" to its default settings? This will overwrite your customizations.`)) return;
                                                setIsResetting(true);
                                                try {
                                                    await resetBrandToDefault(brandName);
                                                    window.location.reload();
                                                } finally {
                                                    setIsResetting(false);
                                                }
                                            }}
                                            disabled={isResetting}
                                            className="flex items-center gap-2 px-4 py-2 rounded-lg bg-[#2E2E2E] hover:bg-[#3A3A3E] text-[#9CA3AF] text-sm font-medium disabled:opacity-50 transition-colors"
                                        >
                                            {isResetting ? (
                                                <>
                                                    <span className="material-symbols-sharp text-base animate-spin" style={{ fontVariationSettings: "'wght' 300" }}>progress_activity</span>
                                                    Resetting...
                                                </>
                                            ) : (
                                                <>
                                                    <span className="material-symbols-sharp text-base" style={{ fontVariationSettings: "'wght' 300" }}>restart_alt</span>
                                                    Reset Brand
                                                </>
                                            )}
                                        </button>
                                    </div>
                                </div>
                            </div>
                        </>
                    )}

                    {activeTab === 'notifications' && (
                        <div className="rounded-[14px] p-6" style={{ backgroundColor: 'var(--bg-secondary)', border: '1px solid var(--border)', boxShadow: 'var(--card-shadow)' }}>
                            <span className="text-base font-semibold mb-4 block" style={{ color: 'var(--text-primary)' }}>Notification Preferences</span>
                            <p className="text-[#6B6B70] text-sm">Notification settings coming soon.</p>
                        </div>
                    )}

                    {activeTab === 'security' && (
                        <div className="rounded-[14px] p-6" style={{ backgroundColor: 'var(--bg-secondary)', border: '1px solid var(--border)', boxShadow: 'var(--card-shadow)' }}>
                            <span className="text-base font-semibold mb-4 block" style={{ color: 'var(--text-primary)' }}>Security Settings</span>
                            <p className="text-[#6B6B70] text-sm">Security settings coming soon.</p>
                        </div>
                    )}

                    {activeTab === 'billing' && (
                        <div className="flex flex-col gap-6">
                            {/* Manage Billing Portal */}
                            {config?.subscription?.plan && config.subscription.plan !== 'starter' && (
                                <div
                                    className="rounded-[14px] p-5 flex items-center justify-between"
                                    style={{ backgroundColor: 'var(--bg-secondary)', border: '1px solid var(--border)', boxShadow: 'var(--card-shadow)' }}
                                >
                                    <div className="flex items-center gap-3">
                                        <span className="material-symbols-sharp text-xl" style={{ color: '#FF5C00', fontVariationSettings: "'FILL' 1, 'wght' 300" }}>credit_card</span>
                                        <div>
                                            <span className="text-sm font-medium block" style={{ color: 'var(--text-primary)' }}>Manage Billing</span>
                                            <span className="text-xs" style={{ color: 'var(--text-muted)' }}>Update payment method, view invoices, or cancel your subscription.</span>
                                        </div>
                                    </div>
                                    <button
                                        onClick={async () => {
                                            try {
                                                const token = await getAuthToken();
                                                const baseUrl = import.meta.env.VITE_API_BASE_URL || '';
                                                const res = await fetch(`${baseUrl}/api/billing/create-portal`, {
                                                    method: 'POST',
                                                    headers: {
                                                        'Content-Type': 'application/json',
                                                        ...(token ? { Authorization: `Bearer ${token}` } : {}),
                                                    },
                                                });
                                                const data = await res.json();
                                                if (!res.ok) throw new Error(data.error || 'Failed to open billing portal');
                                                if (data.url) window.location.href = data.url;
                                            } catch (err: any) {
                                                alert(`Could not open billing portal: ${err.message}`);
                                            }
                                        }}
                                        className="px-4 py-2 rounded-lg text-sm font-medium transition-all"
                                        style={{ backgroundColor: 'var(--bg-tertiary)', color: 'var(--text-primary)', border: '1px solid var(--border)' }}
                                    >
                                        Open Portal
                                    </button>
                                </div>
                            )}
                            <PricingPage
                                currentPlan={config?.subscription?.plan}
                                usage={config?.subscription?.usage}
                                brandId={getBrandRegistryEntry(brandName)?.brandId}
                            />
                        </div>
                    )}
                </div>
            </div>
        </div>
    );
};
