import React from 'react';
import { StrategyTask } from '../types';

interface StrategyDetailViewProps {
    task: StrategyTask;
    onClose: () => void;
    onExecute: () => void;
    onFeedback?: (feedback: 'approved' | 'dismissed' | 'neutral') => void;
}

export const StrategyDetailView: React.FC<StrategyDetailViewProps> = ({ task, onClose, onExecute, onFeedback }) => {
    return (
        <div className="fixed inset-0 z-50 flex items-center justify-center p-4 sm:p-6 animate-fadeIn">
            {/* Backdrop with deeper blur */}
            <div
                className="absolute inset-0 bg-gray-900/60 backdrop-blur-md transition-opacity"
                onClick={onClose}
            ></div>

            {/* Modal Content - Wider & Premium Shadow */}
            <div className="relative w-full max-w-3xl bg-white rounded-2xl shadow-2xl ring-1 ring-black/5 overflow-hidden flex flex-col max-h-[90vh] animate-slideUp">

                {/* Header - Dark "Command Node" Style */}
                <div className="relative px-8 py-6 bg-slate-900 border-b border-slate-800 text-white">
                    {/* Background Pattern */}
                    <div className="absolute inset-0 bg-[url('https://grainy-gradients.vercel.app/noise.svg')] opacity-10 pointer-events-none"></div>

                    <div className="relative z-10">
                        <div className="flex items-center justify-between mb-3">
                            <div className="flex items-center gap-3">
                                <span className={`px-2 py-0.5 rounded text-[10px] font-bold uppercase tracking-widest border ${task.impactScore > 8 ? 'bg-emerald-500/20 text-emerald-300 border-emerald-500/30' : 'bg-blue-500/20 text-blue-300 border-blue-500/30'
                                    }`}>
                                    {task.type.replace('_', ' ')}
                                </span>
                                <span className="text-[10px] font-mono text-slate-400 uppercase tracking-tight">ID: {task.id.slice(0, 8)}</span>
                            </div>
                            <button
                                onClick={onClose}
                                className="text-slate-400 hover:text-white transition-colors bg-white/5 hover:bg-white/10 p-1.5 rounded-full"
                            >
                                <svg className="w-4 h-4" fill="none" viewBox="0 0 24 24" stroke="currentColor"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth="2" d="M6 18L18 6M6 6l12 12" /></svg>
                            </button>
                        </div>
                        <h2 className="text-3xl font-bold tracking-tight text-white mb-1">
                            {task.title}
                        </h2>
                        <div className="flex items-center gap-2 text-xs text-slate-400 font-light">
                            <span>Generated by Neural Strategy Engine</span>
                            <span className="w-1 h-1 rounded-full bg-slate-600"></span>
                            <span>{new Date().toLocaleDateString()}</span>
                        </div>
                    </div>
                </div>

                {/* Scrollable Body */}
                <div className="flex-1 overflow-y-auto bg-slate-50">
                    <div className="p-8 space-y-8">

                        {/* 1. Main Reasoning - Featured Card */}
                        <section className="bg-white rounded-xl p-6 shadow-sm border border-gray-100 relative overflow-hidden group">
                            <div className="absolute top-0 left-0 w-1 h-full bg-blue-500"></div>
                            <h3 className="text-xs font-bold text-slate-400 uppercase tracking-widest mb-4 flex items-center gap-2">
                                <span className="w-2 h-2 bg-blue-500 rounded-full animate-pulse"></span>
                                Strategic Rationale
                            </h3>
                            <p className="text-slate-700 text-lg leading-relaxed font-medium">
                                {task.reasoning}
                            </p>
                        </section>

                        {/* 2. Grid Layout for Metrics & Proof */}
                        <div className="grid grid-cols-1 md:grid-cols-3 gap-6">

                            {/* Left Col: Metrics */}
                            <div className="md:col-span-1 space-y-4">
                                {/* Impact Card */}
                                <div className="bg-white p-5 rounded-xl border border-gray-200 shadow-sm relative overflow-hidden">
                                    <div className="absolute -right-6 -top-6 w-12 h-12 bg-emerald-50 rounded-full blur-xl"></div>
                                    <div className="text-[10px] font-bold text-gray-400 uppercase tracking-wider mb-1">Projected Impact</div>
                                    <div className="flex items-end gap-2">
                                        <div className="text-4xl font-bold text-slate-900 tracking-tighter">{task.impactScore}</div>
                                        <div className="text-sm font-medium text-gray-400 mb-1.5">/10</div>
                                    </div>
                                    <div className="mt-3 w-full bg-gray-100 h-1.5 rounded-full overflow-hidden">
                                        <div className="h-full bg-emerald-500 rounded-full" style={{ width: `${task.impactScore * 10}%` }}></div>
                                    </div>
                                </div>

                                {/* Confidence Card */}
                                <div className="bg-white p-5 rounded-xl border border-gray-200 shadow-sm">
                                    <div className="text-[10px] font-bold text-gray-400 uppercase tracking-wider mb-2">Confidence Level</div>
                                    <div className="flex items-center justify-between">
                                        <div className="px-3 py-1 bg-slate-900 text-white text-sm font-bold rounded-lg shadow-md">
                                            High Confidence
                                        </div>
                                        <span className="text-2xl">🎯</span>
                                    </div>
                                </div>
                            </div>

                            {/* Right Col: Logic & Proof */}
                            <div className="md:col-span-2 space-y-4">
                                {(task.logicExplanation || task.proof) ? (
                                    <div className="bg-white rounded-xl border border-gray-200 shadow-sm p-6 h-full">
                                        <div className="flex items-center justify-between mb-4">
                                            <h3 className="text-xs font-bold text-slate-400 uppercase tracking-wider flex items-center gap-2">
                                                <svg className="w-4 h-4 text-amber-500" fill="none" viewBox="0 0 24 24" stroke="currentColor"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth="2" d="M13 10V3L4 14h7v7l9-11h-7z" /></svg>
                                                Intelligence Brief
                                            </h3>
                                            {task.proof && <span className="text-[9px] bg-slate-100 text-slate-500 px-2 py-0.5 rounded-full border border-slate-200 font-mono">VERIFIED SIGNAL</span>}
                                        </div>

                                        {task.logicExplanation && (
                                            <div className="mb-6">
                                                <h4 className="text-xs font-bold text-slate-900 mb-2">Analysis Model</h4>
                                                <p className="text-sm text-slate-600 leading-relaxed bg-slate-50 p-3 rounded-lg border border-slate-100">
                                                    {task.logicExplanation}
                                                </p>
                                            </div>
                                        )}

                                        {task.proof && (
                                            <div>
                                                <h4 className="text-xs font-bold text-slate-900 mb-2">Data Source Verification</h4>
                                                <blockquote className="relative p-4 border-l-4 border-emerald-500/50 bg-emerald-50/30 rounded-r-lg">
                                                    <p className="text-sm font-medium italic text-slate-700 font-serif">
                                                        "{task.proof}"
                                                    </p>
                                                </blockquote>
                                            </div>
                                        )}
                                    </div>
                                ) : (
                                    <div className="bg-slate-50 rounded-xl border border-dashed border-slate-200 p-6 h-full flex items-center justify-center">
                                        <div className="text-center">
                                            <p className="text-xs text-slate-400 font-mono">No supplementary intelligence data available.</p>
                                            <button className="mt-2 text-[10px] text-blue-500 hover:underline">Request Deep Dive →</button>
                                        </div>
                                    </div>
                                )}
                            </div>
                        </div>

                        {/* 3. Context Links (Horizontal Scroll) */}
                        {task.contextData && task.contextData.length > 0 && (
                            <section>
                                <h3 className="text-[10px] font-bold text-slate-400 uppercase tracking-widest mb-3 pl-1">
                                    References & Signals
                                </h3>
                                <div className="flex gap-3 overflow-x-auto pb-2 scrollbar-hide">
                                    {task.contextData.map((ctx, i) => (
                                        <a
                                            key={i}
                                            href={ctx.url || '#'}
                                            target="_blank"
                                            rel="noreferrer"
                                            className="flex-shrink-0 min-w-[200px] max-w-[280px] p-3 bg-white hover:bg-blue-50/50 border border-gray-200 hover:border-blue-200 rounded-lg group transition-all"
                                        >
                                            <div className="flex items-center gap-2 mb-2">
                                                <span className="text-[9px] font-bold uppercase text-slate-400 bg-slate-50 px-1.5 py-0.5 rounded border border-slate-100 group-hover:bg-white">{ctx.source}</span>
                                            </div>
                                            <div className="text-xs font-medium text-slate-700 line-clamp-2 group-hover:text-blue-700 transition-colors">
                                                {ctx.headline}
                                            </div>
                                        </a>
                                    ))}
                                </div>
                            </section>
                        )}
                    </div>
                </div>

                {/* Footer Actions */}
                <div className="p-5 border-t border-gray-200 bg-white flex items-center justify-between">
                    <button
                        onClick={onClose}
                        className="text-slate-500 hover:text-slate-800 text-xs font-bold uppercase tracking-wider px-4 transition-colors"
                    >
                        Dismiss
                    </button>
                    <div className="flex gap-3">
                        {onFeedback && (
                            <>
                                <button
                                    onClick={() => onFeedback(task.feedback === 'approved' ? 'neutral' : 'approved')}
                                    className={`px-4 py-2.5 text-xs font-bold rounded-lg transition-colors border ${
                                        task.feedback === 'approved'
                                            ? 'bg-emerald-500/15 text-emerald-700 border-emerald-200'
                                            : 'bg-emerald-50 text-emerald-700 border-emerald-100 hover:bg-emerald-100'
                                    }`}
                                >
                                    Approve
                                </button>
                                <button
                                    onClick={() => onFeedback(task.feedback === 'dismissed' ? 'neutral' : 'dismissed')}
                                    className={`px-4 py-2.5 text-xs font-bold rounded-lg transition-colors border ${
                                        task.feedback === 'dismissed'
                                            ? 'bg-rose-500/15 text-rose-700 border-rose-200'
                                            : 'bg-rose-50 text-rose-700 border-rose-100 hover:bg-rose-100'
                                    }`}
                                >
                                    Dismiss
                                </button>
                            </>
                        )}
                        <button className="px-5 py-2.5 text-xs font-bold text-slate-600 bg-slate-100 hover:bg-slate-200 rounded-lg transition-colors border border-slate-200">
                            Edit Brief
                        </button>
                        <button
                            onClick={onExecute}
                            className="px-8 py-2.5 bg-gradient-to-r from-slate-900 to-black hover:from-slate-800 hover:to-gray-900 text-white text-xs font-bold rounded-lg shadow-lg hover:shadow-xl hover:-translate-y-0.5 transition-all uppercase tracking-widest flex items-center gap-2 group ring-1 ring-black/5"
                        >
                            Execute Strategy
                            <svg className="w-4 h-4 text-emerald-400 group-hover:translate-x-1 transition-transform" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                                <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M17 8l4 4m0 0l-4 4m4-4H3" />
                            </svg>
                        </button>
                    </div>
                </div>

            </div>
        </div>
    );
};
